import { 
  Box, 
  Button, 
  Flex, 
  FormControl, 
  FormLabel, 
  Heading, 
  Input, 
  Text, 
  Textarea
} from '@chakra-ui/react'
import Head from 'next/head'
export default function Home() {
  return (
    <>
      <Head>
        <title>Form chakra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex
          minHeight="100vh"
          width="full"
          align="center"
          justifyContent="center"
          backgroundColor="gray.900"
        >
          <Box
            px={12}
            py={12}
            width="full"
            maxWidth="450px"
            textAlign="center"
            boxShadow='lg'
            background='gray.700'
            borderRadius='6px'
          >
            <Heading color="white">
              <Text color='gray.200' fontSize='2xl'>Registration Form</Text>
            </Heading>
            <Box>
              <form autoComplete='off'>
              <Flex justify='space-between'>
                <FormControl isRequired marginTop='15px' width='49%'>
                  <FormLabel color='gray.200'>First name</FormLabel>
                  <Input border='none' outline='none' bgColor='gray.900' focusBorderColor='gray.600' color='gray.200' placeholder='first name' type='text' name='name' />
                </FormControl>
                <FormControl isRequired marginTop='15px' width='49%'>
                  <FormLabel color='gray.200'>Last name</FormLabel>
                  <Input border='none' outline='none' bgColor='gray.900' focusBorderColor='gray.600' color='gray.200' placeholder='last name' type='text' name='name' />
                </FormControl>
              </Flex>
              <FormControl isRequired marginTop='15px'>
                <FormLabel color='gray.200'>Your email</FormLabel>
                <Input border='none' outline='none' bgColor='gray.900' focusBorderColor='gray.600' color='gray.200' placeholder='email' type='email' />
              </FormControl>
              <Flex justify='space-between'>
                <FormControl isRequired marginTop='15px' width='49%'>
                  <FormLabel color='gray.200'>Your address</FormLabel>
                  <Input border='none' outline='none' bgColor='gray.900' focusBorderColor='gray.600' color='gray.200' placeholder='adress' type='text' />
                </FormControl>
                <FormControl isRequired marginTop='15px' width='49%'>
                  <FormLabel color='gray.200'>Your phone</FormLabel>
                  <Input border='none' outline='none' bgColor='gray.900' focusBorderColor='gray.600' color='gray.200' placeholder='phone' type='text' />
              </FormControl>
              </Flex>
              <FormControl isRequired marginTop='15px'>
                <FormLabel color='gray.200'>Your descript message</FormLabel>
                <Textarea border='none' outline='none' bgColor='gray.900' focusBorderColor='gray.600' color='gray.200' placeholder='message' resize='none' />
              </FormControl>
              <Button type='submit' width='full' bgColor='green.200' mt={4} color='gray.400' _hover={{
                color: 'black',
              }}>Register</Button>
              </form>
            </Box>
          </Box>
        </Flex>
      </main>
    </>
  )
}
